import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; //Google Fonts の使用
import './globals.css'; //グローバル CSS のインポート


//Google Fonts の使用
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//Metadata の設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//ルートレイアウトの定義
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
